CREATE TABLE DT_KEY_MT(
KEY varchar(100) not null COMMENT '키'
, ORD number(6) not null COMMENT '순서'
)ENGINE=INNODB COMMENT='전자공시시스템API키';

CREATE INDEX DT_KEY_MT_IDX_PK DT_KEY_MT(KEY);

ALTER TABLE DT_KEY_MT ADD PRIMARY KEY (KEY);



