/* 코드 상세 테이블 생성 */
CREATE TABLE BC_CD_DT(
	  CD_COL	VARCHAR(100)	NOT NULL	COMMENT '코드컬럼'
	, CD		VARCHAR(5)		NOT NULL	COMMENT '코드'
	, CD_NM		VARCHAR(100)	NOT NULL	COMMENT '코드명'
	, CD_VAL	VARCHAR(1000)	NULL		COMMENT '코드값'
	, ORD		DECIMAL(6)		NOT NULL	COMMENT '순서'
	, USE_YN	VARCHAR(1)		NOT NULL	COMMENT '사용여부'
) ENGINE=INNODB COMMENT='코드상세';

ALTER TABLE BC_CD_DT ADD PRIMARY KEY (CD_COL, CD);