/**
 * 전자공시시스템 재무제표 가공 정보
 */
CREATE TABLE IF NOT EXISTS DT_FNLTT_DT (
	  DART_ITM_CD				VARCHAR(10)		NOT NULL	COMMENT '전자공시시스템 종목코드'
	, YR						VARCHAR(4)		NOT NULL	COMMENT '연도(년도)'
	, QT_CD						VARCHAR(5)		NOT NULL	COMMENT '분기코드'
	, BSC_CPT					DECIMAL(20)		NULL		COMMENT '자본'
	, OWN_CPT					DECIMAL(20)		NULL		COMMENT '지배 자본'
	, AST_AMT					DECIMAL(20)		NULL		COMMENT '자산총계'
	, DEBT_AMT					DECIMAL(20)		NULL		COMMENT '부채총계'
	, SAL_AMT					DECIMAL(20)		NULL		COMMENT '매출액'
	, SAL_TOT_INCM_AMT			DECIMAL(20)		NULL		COMMENT '매출총이익'
	, OPR_INCM_AMT				DECIMAL(20)		NULL		COMMENT '영업이익금액'
	, TS_NET_INCM_AMT			DECIMAL(20)		NULL		COMMENT '당기순이익금액'
	, OWN_TS_NET_INCM_AMT		DECIMAL(20)		NULL		COMMENT '지배주주당기순이익금액'
	, TS_BSC_EPS				DECIMAL(20)		NULL		COMMENT '당기기본주당순이익'
	, TS_DLTD_EPS				DECIMAL(20)		NULL		COMMENT '당기희석주당순이익'
	, OPR_BSC_EPS				DECIMAL(20)		NULL		COMMENT '계속영업기본주당순이익'
	, OPR_DLTD_EPS				DECIMAL(20)		NULL		COMMENT '계속영업희석주당순이익'
	, OPR_CSFLW					DECIMAL(20)		NULL		COMMENT '영업활동현금흐름'
	, DEBT_RT					DECIMAL(20)		NULL		COMMENT '부채비율'
	
	, ADD_SAL_AMT				DECIMAL(20)		NULL		COMMENT '합계 매출액'
	, ADD_SAL_TOT_INCM_AMT		DECIMAL(20)		NULL		COMMENT '합계 매출총이익'
	, ADD_OPR_INCM_AMT			DECIMAL(20)		NULL		COMMENT '합계 영업이익금액'
	, ADD_TS_NET_INCM_AMT		DECIMAL(20)		NULL		COMMENT '합계 당기순이익금액'
	, ADD_OWN_TS_NET_INCM_AMT	DECIMAL(20)		NULL		COMMENT '합계 지배주주당기순이익금액'
	, ADD_TS_BSC_EPS			DECIMAL(20)		NULL		COMMENT '합계 당기기본주당순이익'
	, ADD_TS_DLTD_EPS			DECIMAL(20)		NULL		COMMENT '합계 당기희석주당순이익'
	, ADD_OPR_BSC_EPS			DECIMAL(20)		NULL		COMMENT '합계 계속영업기본주당순이익'
	, ADD_OPR_DLTD_EPS			DECIMAL(20)		NULL		COMMENT '합계 계속영업희석주당순이익'
	
) ENGINE=INNODB COMMENT='전자공시시스템 재무제표 가공 정보';

/**
 * 전자공시시스템 재무제표 가공 정보
 */
ALTER TABLE DT_FNLTT_DT ADD PRIMARY KEY (DART_ITM_CD, YR, QT_CD);